name: Update CSRF Badge

on:
  push:
    paths:
      - 'README.md'
  schedule:
    - cron: '0 * * * *'  # Runs hourly

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run badge updater
        run: |
          python generate-badge.py

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update CSRF progress badge" || echo "No changes to commit"
          git pull --rebase origin main
          git push